import re

with open('migrations/versions/__pycache__', 'r', encoding='utf-8') as f:
    content = f.read()

create_tires = \"\"\"
    op.create_table('erp_tires',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('branch_id', sa.Integer(), nullable=False),
        sa.Column('vehicle_id', sa.Integer(), nullable=True),
        sa.Column('serial_number', sa.String(length=100), nullable=False),
        sa.Column('brand', sa.String(length=100), nullable=True),
        sa.Column('size', sa.String(length=50), nullable=True),
        sa.Column('install_date', sa.Date(), nullable=True),
        sa.Column('status', sa.String(length=50), nullable=True),
        sa.Column('retread_date', sa.Date(), nullable=True),
        sa.Column('notes', sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(['branch_id'], ['erp_branches.id'], ),
        sa.ForeignKeyConstraint(['vehicle_id'], ['erp_vehicles.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('serial_number')
    )
    op.create_table('erp_batteries',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('branch_id', sa.Integer(), nullable=False),
        sa.Column('vehicle_id', sa.Integer(), nullable=True),
        sa.Column('serial_number', sa.String(length=100), nullable=False),
        sa.Column('brand', sa.String(length=100), nullable=True),
        sa.Column('capacity', sa.String(length=50), nullable=True),
        sa.Column('install_date', sa.Date(), nullable=True),
        sa.Column('warranty_expiry', sa.Date(), nullable=True),
        sa.Column('status', sa.String(length=50), nullable=True),
        sa.Column('notes', sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(['branch_id'], ['erp_branches.id'], ),
        sa.ForeignKeyConstraint(['vehicle_id'], ['erp_vehicles.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('serial_number')
    )
\"\"\"

drop_tires = \"\"\"
    op.drop_table('erp_batteries')
    op.drop_table('erp_tires')
\"\"\"

if "op.create_table('erp_tires'" not in content:
    content = content.replace("def upgrade():\n    # ### commands auto generated by Alembic - please adjust! ###", "def upgrade():\n    # ### commands auto generated by Alembic - please adjust! ###\n" + create_tires)
    content = content.replace("def downgrade():\n    # ### commands auto generated by Alembic - please adjust! ###", "def downgrade():\n    # ### commands auto generated by Alembic - please adjust! ###\n" + drop_tires)

with open('migrations/versions/__pycache__', 'w', encoding='utf-8') as f:
    f.write(content)

print("Fixed migration for tires and batteries.")
