import re

with open("migrations/versions/b089400cc9e6_add_yard_and_custodyitem.py", "r", encoding="utf-8") as f:
    content = f.read()

create_table = """
    op.create_table('erp_custody_items',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('branch_id', sa.Integer(), nullable=False),
        sa.Column('driver_id', sa.Integer(), nullable=False),
        sa.Column('item_type', sa.String(length=100), nullable=False),
        sa.Column('item_details', sa.String(length=255), nullable=True),
        sa.Column('received_date', sa.Date(), nullable=False),
        sa.Column('returned_date', sa.Date(), nullable=True),
        sa.Column('status', sa.String(length=50), nullable=True),
        sa.Column('notes', sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(['branch_id'], ['erp_branches.id'], ),
        sa.ForeignKeyConstraint(['driver_id'], ['erp_drivers.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
"""

drop_table = """
    op.drop_table('erp_custody_items')
"""

if "op.create_table('erp_custody_items'" not in content:
    content = content.replace("def upgrade():\n    # ### commands auto generated by Alembic - please adjust! ###", "def upgrade():\n    # ### commands auto generated by Alembic - please adjust! ###\n" + create_table)
    content = content.replace("def downgrade():\n    # ### commands auto generated by Alembic - please adjust! ###", "def downgrade():\n    # ### commands auto generated by Alembic - please adjust! ###\n" + drop_table)

with open("migrations/versions/b089400cc9e6_add_yard_and_custodyitem.py", "w", encoding="utf-8") as f:
    f.write(content)

print("Added create_table for erp_custody_items to migration.")
