import glob

files = glob.glob("migrations/versions/b089*.py")
if files:
    with open(files[0], "r", encoding="utf-8") as f:
        content = f.read()

    # The file is broken. Let's just restore it cleanly.
    clean = """\"\"\"Add Yard and CustodyItem

Revision ID: b089400cc9e6
Revises: b7f3db79753a
Create Date: 2026-07-21 23:43:58.431004

\"\"\"
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b089400cc9e6'
down_revision = 'b7f3db79753a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('erp_vehicles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('yard_status', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('yard_condition', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('erp_vehicles', schema=None) as batch_op:
        batch_op.drop_column('yard_condition')
        batch_op.drop_column('yard_status')

    # ### end Alembic commands ###
"""
    with open(files[0], "w", encoding="utf-8") as f:
        f.write(clean)
    print("Restored migration file.")
