"""Add PettyCash model

Revision ID: 12874bded2b7
Revises: cf377f2f0e51
Create Date: 2026-07-22 00:21:30.290357

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12874bded2b7'
down_revision = 'cf377f2f0e51'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
