"""Add category, supplier, last_updated to SparePart

Revision ID: 1d90e14c2194
Revises: 12874bded2b7
Create Date: 2026-07-28 14:11:52.924565

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d90e14c2194'
down_revision = '12874bded2b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    inspector = sa.inspect(conn)

    # --- erp_spare_parts ---
    spare_parts_columns = [col['name'] for col in inspector.get_columns('erp_spare_parts')]
    
    with op.batch_alter_table('erp_spare_parts', schema=None) as batch_op:
        if 'category' not in spare_parts_columns:
            batch_op.add_column(sa.Column('category', sa.String(length=100), nullable=True))
        if 'supplier' not in spare_parts_columns:
            batch_op.add_column(sa.Column('supplier', sa.String(length=150), nullable=True))
        if 'last_updated' not in spare_parts_columns:
            batch_op.add_column(sa.Column('last_updated', sa.DateTime(), nullable=True))

    # --- erp_vehicles ---
    vehicles_columns = [col['name'] for col in inspector.get_columns('erp_vehicles')]
    
    with op.batch_alter_table('erp_vehicles', schema=None) as batch_op:
        if 'current_km' not in vehicles_columns:
            batch_op.add_column(sa.Column('current_km', sa.Integer(), nullable=True))
        if 'odometer' not in vehicles_columns:
            batch_op.add_column(sa.Column('odometer', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('erp_vehicles', schema=None) as batch_op:
        batch_op.drop_column('odometer')
        batch_op.drop_column('current_km')

    with op.batch_alter_table('erp_spare_parts', schema=None) as batch_op:
        batch_op.drop_column('last_updated')
        batch_op.drop_column('supplier')
        batch_op.drop_column('category')

    # ### end Alembic commands ###
