"""add birth_date to erp_drivers

Revision ID: 72becfe50723
Revises: 9dfded86b804
Create Date: 2026-08-24 02:49:34.194577

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72becfe50723'
down_revision = '9dfded86b804'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('erp_drivers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('birth_date', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('erp_drivers', schema=None) as batch_op:
        batch_op.drop_column('birth_date')

    # ### end Alembic commands ###
