"""add missing vehicle columns

Revision ID: 9dfded86b804
Revises: 1d90e14c2194
Create Date: 2026-08-23 13:19:19.267342

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9dfded86b804'
down_revision = '1d90e14c2194'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('erp_vehicles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('current_km', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('odometer', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('pallets', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('load_capacity', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('opcard', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('fuel_card', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('notes', sa.Text(), nullable=True))
        
    with op.batch_alter_table('erp_drivers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('empNotes', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('erp_drivers', schema=None) as batch_op:
        batch_op.drop_column('empNotes')

    with op.batch_alter_table('erp_vehicles', schema=None) as batch_op:
        batch_op.drop_column('notes')
        batch_op.drop_column('fuel_card')
        batch_op.drop_column('opcard')
        batch_op.drop_column('load_capacity')
        batch_op.drop_column('pallets')
        batch_op.drop_column('odometer')
        batch_op.drop_column('current_km')
    # ### end Alembic commands ###
