"""Add Yard and CustodyItem

Revision ID: b089400cc9e6
Revises: b7f3db79753a
Create Date: 2026-07-21 23:43:58.431004

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b089400cc9e6'
down_revision = 'b7f3db79753a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.create_table('erp_custody_items',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('branch_id', sa.Integer(), nullable=False),
        sa.Column('driver_id', sa.Integer(), nullable=False),
        sa.Column('item_type', sa.String(length=100), nullable=False),
        sa.Column('item_details', sa.String(length=255), nullable=True),
        sa.Column('received_date', sa.Date(), nullable=False),
        sa.Column('returned_date', sa.Date(), nullable=True),
        sa.Column('status', sa.String(length=50), nullable=True),
        sa.Column('notes', sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(['branch_id'], ['erp_branches.id'], ),
        sa.ForeignKeyConstraint(['driver_id'], ['erp_drivers.id'], ),
        sa.PrimaryKeyConstraint('id')
    )

    with op.batch_alter_table('erp_vehicles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('yard_status', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('yard_condition', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_table('erp_custody_items')

    with op.batch_alter_table('erp_vehicles', schema=None) as batch_op:
        batch_op.drop_column('yard_condition')
        batch_op.drop_column('yard_status')

    # ### end Alembic commands ###
