"""initial_migration_all_tables

Revision ID: bd8202721dec
Revises: 
Create Date: 2026-07-19 00:58:11.519721

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd8202721dec'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('erp_branches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('erp_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=False),
    sa.Column('doc_type', sa.String(length=50), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=True),
    sa.Column('entity_ref', sa.String(length=255), nullable=True),
    sa.Column('number', sa.String(length=100), nullable=True),
    sa.Column('expiry', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('file_data', sa.Text(), nullable=True),
    sa.Column('mime_type', sa.String(length=50), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('file_path', sa.String(length=255), nullable=False),
    sa.Column('upload_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['erp_branches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('erp_drivers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('iqama_number', sa.String(length=50), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('job_title', sa.String(length=100), nullable=True),
    sa.Column('iqama_expiry', sa.Date(), nullable=True),
    sa.Column('license_expiry', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['erp_branches.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('employee_id'),
    sa.UniqueConstraint('iqama_number')
    )
    op.create_table('erp_spare_parts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=False),
    sa.Column('part_number', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['erp_branches.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('part_number')
    )
    op.create_table('erp_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=True),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['erp_branches.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('erp_vehicles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=False),
    sa.Column('plate_number', sa.String(length=50), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=True),
    sa.Column('v_type', sa.String(length=50), nullable=True),
    sa.Column('serial_number', sa.String(length=100), nullable=True),
    sa.Column('insurance_expiry', sa.Date(), nullable=True),
    sa.Column('istimara_expiry', sa.Date(), nullable=True),
    sa.Column('inspection_expiry', sa.Date(), nullable=True),
    sa.Column('gps_device_id', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['erp_branches.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('plate_number')
    )
    op.create_table('erp_audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('branch_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('target_table', sa.String(length=100), nullable=True),
    sa.Column('target_id', sa.String(length=50), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['erp_branches.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['erp_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('erp_incidents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('driver_id', sa.Integer(), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=False),
    sa.Column('incident_date', sa.Date(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['driver_id'], ['erp_drivers.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['erp_vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('erp_vehicle_custody',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('driver_id', sa.Integer(), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=False),
    sa.Column('received_date', sa.Date(), nullable=False),
    sa.Column('returned_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['driver_id'], ['erp_drivers.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['erp_vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('erp_workshop_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=False),
    sa.Column('entry_date', sa.Date(), nullable=False),
    sa.Column('exit_date', sa.Date(), nullable=True),
    sa.Column('issue_description', sa.Text(), nullable=True),
    sa.Column('mechanic_name', sa.String(length=150), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['vehicle_id'], ['erp_vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('erp_workshop_part_usage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workshop_record_id', sa.Integer(), nullable=False),
    sa.Column('spare_part_id', sa.Integer(), nullable=False),
    sa.Column('quantity_used', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['spare_part_id'], ['erp_spare_parts.id'], ),
    sa.ForeignKeyConstraint(['workshop_record_id'], ['erp_workshop_records.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('erp_workshop_part_usage')
    op.drop_table('erp_workshop_records')
    op.drop_table('erp_vehicle_custody')
    op.drop_table('erp_incidents')
    op.drop_table('erp_audit_logs')
    op.drop_table('erp_vehicles')
    op.drop_table('erp_users')
    op.drop_table('erp_spare_parts')
    op.drop_table('erp_drivers')
    op.drop_table('erp_documents')
    op.drop_table('erp_branches')
    # ### end Alembic commands ###
