"""Add Tires and Batteries

Revision ID: cf377f2f0e51
Revises: b089400cc9e6
Create Date: 2026-07-22 00:13:34.865531

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf377f2f0e51'
down_revision = 'b089400cc9e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
