"""add_remaining_models

Revision ID: e6c199e9c700
Revises: bd8202721dec
Create Date: 2026-07-19 02:11:51.602210

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e6c199e9c700'
down_revision = 'bd8202721dec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('erp_app_settings',
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('erp_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('data', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('erp_purchase_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('item_name', sa.String(length=150), nullable=False),
    sa.Column('cost', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['erp_branches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('erp_schedule_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('task_type', sa.String(length=100), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['erp_branches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('erp_fuel_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=True),
    sa.Column('vehicle_id', sa.Integer(), nullable=True),
    sa.Column('driver_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('prev_odo', sa.Integer(), nullable=True),
    sa.Column('current_odo', sa.Integer(), nullable=True),
    sa.Column('liters', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('cost', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['erp_branches.id'], ),
    sa.ForeignKeyConstraint(['driver_id'], ['erp_drivers.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['erp_vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('erp_handover_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=True),
    sa.Column('driver_id', sa.Integer(), nullable=True),
    sa.Column('vehicle_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['erp_branches.id'], ),
    sa.ForeignKeyConstraint(['driver_id'], ['erp_drivers.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['erp_vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('erp_washing_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=True),
    sa.Column('vehicle_id', sa.Integer(), nullable=True),
    sa.Column('driver_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['erp_branches.id'], ),
    sa.ForeignKeyConstraint(['driver_id'], ['erp_drivers.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['erp_vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('erp_washing_records')
    op.drop_table('erp_handover_records')
    op.drop_table('erp_fuel_records')
    op.drop_table('erp_schedule_data')
    op.drop_table('erp_purchase_records')
    op.drop_table('erp_snapshots')
    op.drop_table('erp_app_settings')
    # ### end Alembic commands ###
